-- ============================================================
-- Script SQL para Supabase del proyecto IoT ESP32
-- Ejecutar en el SQL Editor de Supabase
-- Adaptado para trabajar solo con datos de humedad
-- ============================================================

create table if not exists public.humedad (
    id bigint generated by default as identity primary key,
    humedad numeric(5,2) not null,
    fecha_hora timestamp without time zone default now() not null
);

create index if not exists humedad_fecha_idx on public.humedad (fecha_hora desc);

-- Datos de ejemplo opcionales
insert into public.humedad (humedad, fecha_hora)
values
    (45.5, now() - interval '6 days'),
    (48.2, now() - interval '6 days' + interval '1 hour'),
    (52.0, now() - interval '5 days'),
    (55.8, now() - interval '5 days' + interval '2 hours'),
    (60.3, now() - interval '4 days'),
    (63.7, now() - interval '4 days' + interval '3 hours'),
    (58.4, now() - interval '3 days'),
    (54.2, now() - interval '3 days' + interval '4 hours'),
    (50.1, now() - interval '2 days'),
    (47.9, now() - interval '2 days' + interval '5 hours'),
    (72.5, now() - interval '1 day'),
    (75.1, now() - interval '1 day' + interval '2 hours'),
    (38.5, now() - interval '5 hours'),
    (42.3, now() - interval '4 hours'),
    (46.7, now() - interval '3 hours'),
    (51.2, now() - interval '2 hours'),
    (56.8, now() - interval '1 hour'),
    (59.4, now() - interval '30 minutes'),
    (62.1, now() - interval '10 minutes'),
    (64.5, now());
